version: "3"  

tasks:  
  default:
    cmds:  
      - task: generate  
  generate:  
    aliases:
      - gen  
    desc: "Generate code from proto files"  
    cmds:  
      - protoc -I proto proto/auth.proto --go_out=./gen/auth/ --go_opt=paths=source_relative --go-grpc_out=./gen/auth/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/diary.proto --go_out=./gen/diary/ --go_opt=paths=source_relative --go-grpc_out=./gen/diary/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/media.proto --go_out=./gen/media/ --go_opt=paths=source_relative --go-grpc_out=./gen/media/ --go-grpc_opt=paths=source_relative